# Generated by Django 3.2.9 on 2021-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariresan', '0002_auto_20211114_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorinfo',
            name='gender',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
