# Generated by Django 3.2.9 on 2021-11-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariresan', '0003_alter_instructorinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorinfo',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
