# Generated by Django 3.2.9 on 2021-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yariresan', '0005_auto_20211115_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
